version: '3.4'

services:
    authorization.api:
        image: authorization.api
        build:
            context: .
            dockerfile: Authorization.API/Dockerfile
        ports:
            - 8020:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        restart: on-failure
        depends_on:
            - sqlServer
            - rabbitMQ

    offices.api:
        image: offices.api
        build:
            context: .
            dockerfile: Offices.API/Dockerfile
        ports:
            - 8021:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - postgreSqlServer
            - rabbitMQ

    profiles.api:
        image: profile.api
        build:
              context: .
              dockerfile: Profiles.API/Dockerfile
        ports:
            - 8022:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - sqlServer
            - rabbitMQ

    services.api:
        image: services.api
        build:
            context: .
            dockerfile: Services.API/Dockerfile
        ports:
            - 8023:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        restart: on-failure
        depends_on:
            - sqlServer
            - rabbitMQ

    sqlServer:
        image: mcr.microsoft.com/mssql/server:2022-latest
        user: root
        volumes:
            - sqlServerData:/var/opt/mssql/data
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=AAbbCC123
        ports:
            - 1442:1433

    postgreSqlServer:
        image: postgres:latest
        user: postgres
        volumes:
            - postgreSqlData:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=123
        ports:
            - 1443:5432

    rabbitMQ:
        image: rabbitmq:management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        volumes:
            - rabbitMQ:/var/lib/rabbitmq
        hostname: rabbit

volumes:
    sqlServerData:
    postgreSqlData:
    rabbitMQ:
